[package]
name = "rust-playground"
version = "0.1.1"
authors = ["Brian Pfeil <brian.pfeil@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
