[package]
name = "rust-playground"
version = "0.1.0"
authors = ["Brian Pfeil <brian.pfeil@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"
futures = { version = "0.3.*" }
tokio = {version = "0.2.*", features = ["full"] }